<?php

namespace CSGOTalk\siteBundle\Entity;

/**
 * BestOfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BestOfRepository extends \Doctrine\ORM\EntityRepository
{
}
