<?php

namespace CSGOTalk\siteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TeamPlayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamPlayerRepository extends EntityRepository
{
	public function getTeam()
	{
	    $qb = $this->createQueryBuilder('TeamPlayer');

	    $qb
	      	->leftjoin('TeamPlayer.team', 'Team')
	      	->join('TeamPlayer.player', 'Player')
	      	->addSelect('Team')
	      	->addSelect('Player')
	    ;

	    return $qb
	      	->getQuery()
	      	->getResult()
	    ;
	}
}
