csgo_talksite_homepage:
    path:    /home
    defaults: { _controller: CSGOTalksiteBundle:Site:index }

csgo_talksite_threads:
    path:    /threads
    defaults: { _controller: CSGOTalksiteBundle:Site:threads }

csgo_talksite_profile:
    path:    /profile
    defaults: { _controller: CSGOTalksiteBundle:Site:profile }