csgo_talksite_homepage:
    path:    /home
    defaults: { _controller: CSGOTalksiteBundle:Site:index }

csgo_talksite_threads:
    path:    /threads
    defaults: { _controller: CSGOTalksiteBundle:Site:threads }

csgo_talksite_add_thread:
    path:    /add_thread
    defaults: { _controller: CSGOTalksiteBundle:Site:createThread}

csgo_talksite_show_thread:
    path:     /thread/{id}
    defaults: { _controller: CSGOTalksiteBundle:Site:thread }
    requirements: 
        id: \d+

csgo_talksite_add_message:
    path:     /add_message/{id}
    defaults: { _controller: CSGOTalksiteBundle:Site:addMessage }
    requirements: 
        id: \d+

csgo_talksite_error_connected_status:
    path:     /error
    defaults: { _controller: CSGOTalksiteBundle:Site:errorConnected }